# Generated by Django 4.2.5 on 2023-10-07 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(help_text='Enter the price as an integer (maximum 99999).', validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
