# Generated by Django 4.2.5 on 2023-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='dishes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantities',
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
    ]
