# Generated by Django 4.2.5 on 2023-10-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_products_order_dishes_remove_order_quantities_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
